version: "3.8"

services:
  db:
    image: postgres:12
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - project/.env
    ports:
      - 5433:5432
  redis:
    image: redis:alpine
    container_name: redis
  bot:
    image: rigorich/le_bot_de_python:bot
    container_name: bot
    command: bash -c "python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python run_pooling.py &
      celery -A dtb worker --loglevel=INFO &
      celery -A dtb beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler &
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      - DJANGO_DEBUG='False'
    env_file:
      - project/.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: